// Generated by gencpp from file yolov2_ros/YoloDetect.msg
// DO NOT EDIT!


#ifndef YOLOV2_ROS_MESSAGE_YOLODETECT_H
#define YOLOV2_ROS_MESSAGE_YOLODETECT_H

#include <ros/service_traits.h>


#include <yolov2_ros/YoloDetectRequest.h>
#include <yolov2_ros/YoloDetectResponse.h>


namespace yolov2_ros
{

struct YoloDetect
{

typedef YoloDetectRequest Request;
typedef YoloDetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct YoloDetect
} // namespace yolov2_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yolov2_ros::YoloDetect > {
  static const char* value()
  {
    return "0c98907c2772621acd431740725bdb9a";
  }

  static const char* value(const ::yolov2_ros::YoloDetect&) { return value(); }
};

template<>
struct DataType< ::yolov2_ros::YoloDetect > {
  static const char* value()
  {
    return "yolov2_ros/YoloDetect";
  }

  static const char* value(const ::yolov2_ros::YoloDetect&) { return value(); }
};


// service_traits::MD5Sum< ::yolov2_ros::YoloDetectRequest> should match 
// service_traits::MD5Sum< ::yolov2_ros::YoloDetect > 
template<>
struct MD5Sum< ::yolov2_ros::YoloDetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yolov2_ros::YoloDetect >::value();
  }
  static const char* value(const ::yolov2_ros::YoloDetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolov2_ros::YoloDetectRequest> should match 
// service_traits::DataType< ::yolov2_ros::YoloDetect > 
template<>
struct DataType< ::yolov2_ros::YoloDetectRequest>
{
  static const char* value()
  {
    return DataType< ::yolov2_ros::YoloDetect >::value();
  }
  static const char* value(const ::yolov2_ros::YoloDetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yolov2_ros::YoloDetectResponse> should match 
// service_traits::MD5Sum< ::yolov2_ros::YoloDetect > 
template<>
struct MD5Sum< ::yolov2_ros::YoloDetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yolov2_ros::YoloDetect >::value();
  }
  static const char* value(const ::yolov2_ros::YoloDetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolov2_ros::YoloDetectResponse> should match 
// service_traits::DataType< ::yolov2_ros::YoloDetect > 
template<>
struct DataType< ::yolov2_ros::YoloDetectResponse>
{
  static const char* value()
  {
    return DataType< ::yolov2_ros::YoloDetect >::value();
  }
  static const char* value(const ::yolov2_ros::YoloDetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOLOV2_ROS_MESSAGE_YOLODETECT_H
